### PR TITLE
support laravel nova 4

### PR DESCRIPTION
**Pull request by anditsung**
add dark mode and support for laravel nova 4

### CODE REVIEW

**Comment by bashgeek** [comment]
@dillingham Same question here: Don't want to seem impatient here, just gonna ask now to avoid disappointment down the line: Are you still maintaining this repo and plan to merge and publish this in the near future or should we rather move on with a fork? Thanks a lot!

**Comment by EdgarSedov** [comment]
Also interested in this

**Comment by bashgeek** [comment]
Seems like this is kind of abandoned for now. If anybody is looking for a working Nova 4 version, here is our fork with this PR applied and used in production by us already:
https://github.com/blendbyte/nova-attach-many

**Comment by anditsung** [comment]
> Seems like this is kind of abandoned for now. If anybody is looking for a working Nova 4 version, here is our fork with this PR applied and used in production by us already:
> https://github.com/blendbyte/nova-attach-many

any issues on your end?
i have use this for production yet

**Comment by bashgeek** [comment]
> any issues on your end? i havent use this for production yet

All good so far!

**Comment by NoahNxT** [comment]
@anditsung solve conflict of your branch so this can be merged :)

**Comment by NoahNxT** [comment]
@dillingham this also works without issues, please merge!

**Comment by dillingham** [comment]
Thanks for the PR, I just got my hands on nova 4.. I'll merge when test it out

**Comment by asamofal** [comment]
I'm very interested in this PR as well...

**Comment by nathan-io** [comment]
I'd love to see this merged as well!

**Pull request merged**
