### PR TITLE
Add preview seleted items

### PR DESCRIPTION
**Pull request by ahmedkandel**
`->showPreview()` option to show checkbox which toggles "only selected items" preview.

### CODE REVIEW

**Comment by dillingham** [comment]
@ahmedkandel this is great! Very useful addition.. thank you for the PR

What do you think about

**Keeping the header and search when previewing**
Allow for easy deselecting & wouldn't jump as much when toggling

**Maybe showSelected instead of showPreview**
I like preview, just wondering if "selected" might be more universal 🤔 

Thanks again 😄

**Comment by ahmedkandel** [comment]
@dillingham me who have to thank you for the great packages.

I think the wording "Selected or Preview" is somehow connected to the "Toolbar & Search",

**Preview** approach "like GitHub comment preview" is valid to have a final look before saving and make sure you selected the correct items otherwise deselect wrong ones. while for the toggling jump we could use an overlay as following:

screenshot_2

screenshot_1

**Show (Only) Seleted** approach is valid as a filter but may interfere with toolbar search and select all functionality. I think will confuse the user.

May we use the wording combined as following:

screenshot_4

What do you think?

**Comment by dillingham** [comment]
Ok I agree. I like the second option "Selected Items (3)" but with Preview [ x ]
We can always offer a lang file option to change it later.
Keeping it as preview is good because help text may run longer.
I also like "Selected Items" for when it comes time to translate this in a lang file.
I think the header is a good way to keep the header height from making it jump too 👍

**Comment by ahmedkandel** [comment]
Good, will make a new commit with header overlay "Selected Items (n)" and keep the checkbox as "Preview", both will be translatable in order to offer language file later on.

Also will fix the following scenario: when deselecting an item in preview mode the select all checkbox will be activated as it considers all items are selected which is not true.

**Pull request merged**
