### PR TITLE
Allow help text to contain HTML

### LINKED ISSUE #14: Help Text should work with HTML
The help text should be displayed using the `<help-text>` component, which will allow HTML to be passed through.

```
<help-text class="help-text mt-2" v-if="showHelpText"> {{ field.helpText }} </help-text>
```

Right now it is using a `<span>` tag.

```
<span v-if="field.helpText" class="pr-2">{{ field.helpText }}</span>
```

To reproduce:

```
AttachMany::make('Permissions')->help('You shall <strong>not pass!</strong>'),
```

### PR DESCRIPTION
**Pull request by niladam**
This pull adds a small modification, allowing the `help` to contain HTML text.

The help text appears underneath the selection, on a single line.

Should fix #14 :)

Screenshot attached.

screenshot

### CODE REVIEW

**Comment by niladam** [comment]
hey @dillingham - are you okay buddy ?

**Comment by dillingham** [comment]
Thanks for the PR! Sorry was super tied down with some work stuff.

Im going to tweak it a little and inline like so
error-with-tip

**Comment by niladam** [comment]
I wouldn't have done that. What happens if a longer line needs to be added there ? Say something like: "You need to make sure to always select at least 2 categories, and you can also use the search preview at the top" :)

**Comment by dillingham** [comment]
@niladam good point, added a tweak to allow for long text 

fix

**Comment by niladam** [comment]
Great job! I didn't even think about that.

**Pull request merged**
